name: Moodle Cron

on:
  schedule:
    - cron: "*/5 * * * *"   # Ejecuta cada 5 minutos automáticamente
  workflow_dispatch:         # Permite ejecución manual también

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar cron de Moodle
        run: |
          curl -A "Mozilla/5.0" "https://retox.walver.top/admin/cron.php?password=Retox2025"
